default: &default
  adapter: postgresql
  pool: 25
  timeout: 5000

development:
  <<: *default
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: tuns_development

test:
  <<: *default
  database: tuns_test

production:
  <<: *default
  database: tuns_production
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
