development:
  twitter:
    app_id: a25jThCWPyuqL6bcKHi04vrkL
    secret: 0v9OF8NfSw6ytMlZh7Nplyy157QgJUW2YMxrWuRhW4AHlw5f1c

production:
  twitter:
    app_id: 
    secret: 

staging:
  twitter:
    app_id: 
    secret: 