development:
  consumer_key: QOSElkYp9AUZaVPtzAC3A3Bvt
  consumer_secret: zo353upXxMBDgGAhtOakv8Xn4F90MX2yzcQUYfEjRbZuYgnyXw
  access_token:  313166323-w7vaseluMTEHd5rXZAkTY2hq4TpJyOin42ygctwG
  access_token_secret: m2XdktzxwpDGRsE8c0NsIXqBssCeJG19Rc9cbm89nzTXs

production:
  consumer_key: QOSElkYp9AUZaVPtzAC3A3Bvt
  consumer_secret: zo353upXxMBDgGAhtOakv8Xn4F90MX2yzcQUYfEjRbZuYgnyXw
  access_token:  313166323-w7vaseluMTEHd5rXZAkTY2hq4TpJyOin42ygctwG
  access_token_secret: m2XdktzxwpDGRsE8c0NsIXqBssCeJG19Rc9cbm89nzTXs

staging:
  app_id: 
  secret: