development:
  consumer_key: <%= ENV['TW_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TW_CONSUMER_SECRET'] %>
  access_token:  <%= ENV['TW_ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['TW_ACCESS_TOKEN_SECRET'] %>

production:
  consumer_key: <%= ENV['TW_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TW_CONSUMER_SECRET'] %>
  access_token:  <%= ENV['TW_ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['TW_ACCESS_TOKEN_SECRET'] %>

staging:
  consumer_key: <%= ENV['TW_CONSUMER_KEY'] %>
  consumer_secret: <%= ENV['TW_CONSUMER_SECRET'] %>
  access_token:  <%= ENV['TW_ACCESS_TOKEN'] %>
  access_token_secret: <%= ENV['TW_ACCESS_TOKEN_SECRET'] %>